### ISSUE TITLE
How do we get `p4est_package_id`?

### ISSUE THREAD

**Issue by ranocha** [trixi-framework/p4est-bindings-clang-jl#3]
It is declared in

https://github.com/trixi-framework/p4est-bindings-clang-jl/blob/0a1065444836f8ba8e49cad78534e3e00269a479/p4est_include/p4est_base.h#L322

and defined in

https://github.com/cburstedde/p4est/blob/45ea68a91d11ee15172bc8e6336ed62c91f09cf4/src/p4est_base.c#L27

However, it is not contained in the output generated by Clang.jl. We use it in Trixi.jl to avoid initializing `p4est` multiple times at

https://github.com/trixi-framework/Trixi.jl/blob/189211d9b101dc127d1d2580d4fd85db0639f1b9/src/auxiliary/p4est.jl#L16-L18

How can we get it from the new bindings generated via Clang.jl?

**Comment by ranocha** [comment]
Answer: We can use
```julia
p4est_package_id = unsafe_load(
    cglobal((:p4est_package_id, P4est.LibP4est.libp4est), Cint)
  )
```
but we should decide whether to provide a nice API for this.

**Comment by sloede** [comment]
Thanks for checking this out! Yes, I agree we should provide an API for it, using our particular use case as a motivation. I wonder if it is sufficient to load it once or if it may change during the runtime, in which case we might need to provide it as a function.

**Comment by ranocha** [comment]
It needs to be a function since it is (or can be) updated when calling `p4est_init`.
